### ISSUE TITLE
how to change the 「github」 address  on navigation

### ISSUE THREAD

**Issue by Linkding** [brianmaierjr/long-haul#36]
I had search the config.yml, but it seems have not this config.

```
navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
```
